<?php

declare(strict_types=1);

function reviews_seed_reviews(): array
{
	$seedImagePool = [
		'assets/images/HotelHomePage.png',
		'assets/images/AboutUs.png',
		'assets/images/RestaurantSunsetLagoon.png',
		'assets/images/RestaurantFieryBlaze.png',
		'assets/images/SpaRoom.png',
		'assets/images/Suite1.png',
		'assets/images/Suite2.png',
		'assets/images/Suite3.png',
		'assets/images/parking1.png',
		'assets/images/Sustainability.png',
		'assets/images/home/Cafe.png',
	];

	$pickSeedImage = function () use ($seedImagePool): string {
		$idx = random_int(0, count($seedImagePool) - 1);
		return $seedImagePool[$idx];
	};

	return [
		[
			'name' => 'Alicia T.',
			'rating' => 5,
			'title' => 'Perfect weekend getaway',
			'body' => 'Smooth check-in, spotless room, and the view at sunrise was unreal. We loved how calm the lobby felt even when it was busy.',
			'categories' => ['room', 'views', 'cleanliness', 'service'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 36,
		],
		[
			'name' => 'Marcus L.',
			'rating' => 4,
			'title' => 'Great amenities, minor wait',
			'body' => 'Facilities were excellent and the spa was a highlight. Only downside was a short wait during peak dinner time, but staff handled it well.',
			'categories' => ['amenities', 'service', 'food'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 52,
		],
		[
			'name' => 'Nur S.',
			'rating' => 5,
			'title' => 'Best views from the lounge',
			'body' => 'The skyline view from the lounge is stunning. Clean, quiet, and very comfortable. Will definitely come back for another staycation.',
			'categories' => ['views', 'room', 'cleanliness'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 60,
		],
		[
			'name' => 'Ethan P.',
			'rating' => 3,
			'title' => 'Good stay, parking could improve',
			'body' => 'Room was comfortable and clean. Parking directions were slightly confusing at night, but overall the experience was still decent.',
			'categories' => ['room', 'cleanliness'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 72,
		],
		[
			'name' => 'Hannah K.',
			'rating' => 5,
			'title' => 'Service felt genuinely warm',
			'body' => 'Every staff member we met was friendly and attentive. The little details made the stay feel special. Highly recommended for families.',
			'categories' => ['service', 'amenities'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 84,
		],
		[
			'name' => 'Daniel R.',
			'rating' => 4,
			'title' => 'Clean rooms and good breakfast',
			'body' => 'Breakfast had a solid range and everything tasted fresh. The room was well-kept and the bed was super comfortable.',
			'categories' => ['food', 'room', 'cleanliness'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 96,
		],
		[
			'name' => 'Priya M.',
			'rating' => 5,
			'title' => 'Spa day was amazing',
			'body' => 'Booked a spa session and it was honestly the best part of the trip. Quiet, relaxing, and the facilities were immaculate.',
			'categories' => ['amenities', 'cleanliness', 'service'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 112,
		],
		[
			'name' => 'Jason W.',
			'rating' => 4,
			'title' => 'Nice cafe and common areas',
			'body' => 'The cafe downstairs is convenient and the common areas are great for working. Wi‑Fi was stable throughout the day.',
			'categories' => ['amenities', 'food', 'service'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 130,
		],
		[
			'name' => 'Siti A.',
			'rating' => 5,
			'title' => 'Super clean and quiet',
			'body' => 'I’m very picky about cleanliness and this place was excellent. Quiet at night and the room had everything I needed.',
			'categories' => ['cleanliness', 'room'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 148,
		],
		[
			'name' => 'Ken J.',
			'rating' => 5,
			'title' => 'Beautiful design and atmosphere',
			'body' => 'The overall vibe is classy and relaxing. The lounge seating is comfortable and the staff were helpful with local recommendations.',
			'categories' => ['service', 'amenities', 'views'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 160,
		],
		[
			'name' => 'Mei X.',
			'rating' => 3,
			'title' => 'Good food, room a bit warm',
			'body' => 'Restaurant was tasty and service was quick. The room temperature took a while to cool down, but it was fine after that.',
			'categories' => ['food', 'service', 'room'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 176,
		],
		[
			'name' => 'Olivia B.',
			'rating' => 5,
			'title' => 'Loved the amenities',
			'body' => 'Gym was well-equipped and not crowded. Everything felt polished and thoughtfully designed. Would recommend for business trips too.',
			'categories' => ['amenities', 'service', 'cleanliness'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 190,
		],

		// Duplicates preserved (existing page behaviour/data volume)
		[
			'name' => 'Alicia T.',
			'rating' => 5,
			'title' => 'Perfect weekend getaway',
			'body' => 'Smooth check-in, spotless room, and the view at sunrise was unreal. We loved how calm the lobby felt even when it was busy.',
			'categories' => ['room', 'views', 'cleanliness', 'service'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 36,
		],
		[
			'name' => 'Marcus L.',
			'rating' => 4,
			'title' => 'Great amenities, minor wait',
			'body' => 'Facilities were excellent and the spa was a highlight. Only downside was a short wait during peak dinner time, but staff handled it well.',
			'categories' => ['amenities', 'service', 'food'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 52,
		],
		[
			'name' => 'Nur S.',
			'rating' => 5,
			'title' => 'Best views from the lounge',
			'body' => 'The skyline view from the lounge is stunning. Clean, quiet, and very comfortable. Will definitely come back for another staycation.',
			'categories' => ['views', 'room', 'cleanliness'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 60,
		],
		[
			'name' => 'Ethan P.',
			'rating' => 3,
			'title' => 'Good stay, parking could improve',
			'body' => 'Room was comfortable and clean. Parking directions were slightly confusing at night, but overall the experience was still decent.',
			'categories' => ['room', 'cleanliness'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 72,
		],
		[
			'name' => 'Hannah K.',
			'rating' => 5,
			'title' => 'Service felt genuinely warm',
			'body' => 'Every staff member we met was friendly and attentive. The little details made the stay feel special. Highly recommended for families.',
			'categories' => ['service', 'amenities'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 84,
		],
		[
			'name' => 'Daniel R.',
			'rating' => 4,
			'title' => 'Clean rooms and good breakfast',
			'body' => 'Breakfast had a solid range and everything tasted fresh. The room was well-kept and the bed was super comfortable.',
			'categories' => ['food', 'room', 'cleanliness'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 96,
		],
		[
			'name' => 'Priya M.',
			'rating' => 5,
			'title' => 'Spa day was amazing',
			'body' => 'Booked a spa session and it was honestly the best part of the trip. Quiet, relaxing, and the facilities were immaculate.',
			'categories' => ['amenities', 'cleanliness', 'service'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 112,
		],
		[
			'name' => 'Jason W.',
			'rating' => 4,
			'title' => 'Nice cafe and common areas',
			'body' => 'The cafe downstairs is convenient and the common areas are great for working. Wi‑Fi was stable throughout the day.',
			'categories' => ['amenities', 'food', 'service'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 130,
		],
		[
			'name' => 'Siti A.',
			'rating' => 5,
			'title' => 'Super clean and quiet',
			'body' => 'I’m very picky about cleanliness and this place was excellent. Quiet at night and the room had everything I needed.',
			'categories' => ['cleanliness', 'room'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 148,
		],
		[
			'name' => 'Ken J.',
			'rating' => 5,
			'title' => 'Beautiful design and atmosphere',
			'body' => 'The overall vibe is classy and relaxing. The lounge seating is comfortable and the staff were helpful with local recommendations.',
			'categories' => ['service', 'amenities', 'views'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 160,
		],
		[
			'name' => 'Mei X.',
			'rating' => 3,
			'title' => 'Good food, room a bit warm',
			'body' => 'Restaurant was tasty and service was quick. The room temperature took a while to cool down, but it was fine after that.',
			'categories' => ['food', 'service', 'room'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 176,
		],
		[
			'name' => 'Olivia B.',
			'rating' => 5,
			'title' => 'Loved the amenities',
			'body' => 'Gym was well-equipped and not crowded. Everything felt polished and thoughtfully designed. Would recommend for business trips too.',
			'categories' => ['amenities', 'service', 'cleanliness'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 190,
		],

		[
			'name' => 'Alicia T.',
			'rating' => 5,
			'title' => 'Perfect weekend getaway',
			'body' => 'Smooth check-in, spotless room, and the view at sunrise was unreal. We loved how calm the lobby felt even when it was busy.',
			'categories' => ['room', 'views', 'cleanliness', 'service'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 36,
		],
		[
			'name' => 'Marcus L.',
			'rating' => 4,
			'title' => 'Great amenities, minor wait',
			'body' => 'Facilities were excellent and the spa was a highlight. Only downside was a short wait during peak dinner time, but staff handled it well.',
			'categories' => ['amenities', 'service', 'food'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 52,
		],
		[
			'name' => 'Nur S.',
			'rating' => 5,
			'title' => 'Best views from the lounge',
			'body' => 'The skyline view from the lounge is stunning. Clean, quiet, and very comfortable. Will definitely come back for another staycation.',
			'categories' => ['views', 'room', 'cleanliness'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 60,
		],
		[
			'name' => 'Ethan P.',
			'rating' => 3,
			'title' => 'Good stay, parking could improve',
			'body' => 'Room was comfortable and clean. Parking directions were slightly confusing at night, but overall the experience was still decent.',
			'categories' => ['room', 'cleanliness'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 72,
		],
		[
			'name' => 'Hannah K.',
			'rating' => 5,
			'title' => 'Service felt genuinely warm',
			'body' => 'Every staff member we met was friendly and attentive. The little details made the stay feel special. Highly recommended for families.',
			'categories' => ['service', 'amenities'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 84,
		],
		[
			'name' => 'Daniel R.',
			'rating' => 4,
			'title' => 'Clean rooms and good breakfast',
			'body' => 'Breakfast had a solid range and everything tasted fresh. The room was well-kept and the bed was super comfortable.',
			'categories' => ['food', 'room', 'cleanliness'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 96,
		],
		[
			'name' => 'Priya M.',
			'rating' => 5,
			'title' => 'Spa day was amazing',
			'body' => 'Booked a spa session and it was honestly the best part of the trip. Quiet, relaxing, and the facilities were immaculate.',
			'categories' => ['amenities', 'cleanliness', 'service'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 112,
		],
		[
			'name' => 'Jason W.',
			'rating' => 4,
			'title' => 'Nice cafe and common areas',
			'body' => 'The cafe downstairs is convenient and the common areas are great for working. Wi‑Fi was stable throughout the day.',
			'categories' => ['amenities', 'food', 'service'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 130,
		],
		[
			'name' => 'Siti A.',
			'rating' => 5,
			'title' => 'Super clean and quiet',
			'body' => 'I’m very picky about cleanliness and this place was excellent. Quiet at night and the room had everything I needed.',
			'categories' => ['cleanliness', 'room'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 148,
		],
		[
			'name' => 'Ken J.',
			'rating' => 5,
			'title' => 'Beautiful design and atmosphere',
			'body' => 'The overall vibe is classy and relaxing. The lounge seating is comfortable and the staff were helpful with local recommendations.',
			'categories' => ['service', 'amenities', 'views'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 160,
		],
		[
			'name' => 'Mei X.',
			'rating' => 3,
			'title' => 'Good food, room a bit warm',
			'body' => 'Restaurant was tasty and service was quick. The room temperature took a while to cool down, but it was fine after that.',
			'categories' => ['food', 'service', 'room'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 176,
		],
		[
			'name' => 'Olivia B.',
			'rating' => 5,
			'title' => 'Loved the amenities',
			'body' => 'Gym was well-equipped and not crowded. Everything felt polished and thoughtfully designed. Would recommend for business trips too.',
			'categories' => ['amenities', 'service', 'cleanliness'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 190,
		],

		[
			'name' => 'Alicia T.',
			'rating' => 5,
			'title' => 'Perfect weekend getaway',
			'body' => 'Smooth check-in, spotless room, and the view at sunrise was unreal. We loved how calm the lobby felt even when it was busy.',
			'categories' => ['room', 'views', 'cleanliness', 'service'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 36,
		],
		[
			'name' => 'Marcus L.',
			'rating' => 4,
			'title' => 'Great amenities, minor wait',
			'body' => 'Facilities were excellent and the spa was a highlight. Only downside was a short wait during peak dinner time, but staff handled it well.',
			'categories' => ['amenities', 'service', 'food'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 52,
		],
		[
			'name' => 'Nur S.',
			'rating' => 5,
			'title' => 'Best views from the lounge',
			'body' => 'The skyline view from the lounge is stunning. Clean, quiet, and very comfortable. Will definitely come back for another staycation.',
			'categories' => ['views', 'room', 'cleanliness'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 60,
		],
		[
			'name' => 'Ethan P.',
			'rating' => 3,
			'title' => 'Good stay, parking could improve',
			'body' => 'Room was comfortable and clean. Parking directions were slightly confusing at night, but overall the experience was still decent.',
			'categories' => ['room', 'cleanliness'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 72,
		],
		[
			'name' => 'Hannah K.',
			'rating' => 5,
			'title' => 'Service felt genuinely warm',
			'body' => 'Every staff member we met was friendly and attentive. The little details made the stay feel special. Highly recommended for families.',
			'categories' => ['service', 'amenities'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 84,
		],
		[
			'name' => 'Daniel R.',
			'rating' => 4,
			'title' => 'Clean rooms and good breakfast',
			'body' => 'Breakfast had a solid range and everything tasted fresh. The room was well-kept and the bed was super comfortable.',
			'categories' => ['food', 'room', 'cleanliness'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 96,
		],
		[
			'name' => 'Priya M.',
			'rating' => 5,
			'title' => 'Spa day was amazing',
			'body' => 'Booked a spa session and it was honestly the best part of the trip. Quiet, relaxing, and the facilities were immaculate.',
			'categories' => ['amenities', 'cleanliness', 'service'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 112,
		],
		[
			'name' => 'Jason W.',
			'rating' => 4,
			'title' => 'Nice cafe and common areas',
			'body' => 'The cafe downstairs is convenient and the common areas are great for working. Wi‑Fi was stable throughout the day.',
			'categories' => ['amenities', 'food', 'service'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 130,
		],
		[
			'name' => 'Siti A.',
			'rating' => 5,
			'title' => 'Super clean and quiet',
			'body' => 'I’m very picky about cleanliness and this place was excellent. Quiet at night and the room had everything I needed.',
			'categories' => ['cleanliness', 'room'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 148,
		],
		[
			'name' => 'Ken J.',
			'rating' => 5,
			'title' => 'Beautiful design and atmosphere',
			'body' => 'The overall vibe is classy and relaxing. The lounge seating is comfortable and the staff were helpful with local recommendations.',
			'categories' => ['service', 'amenities', 'views'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 160,
		],
		[
			'name' => 'Mei X.',
			'rating' => 3,
			'title' => 'Good food, room a bit warm',
			'body' => 'Restaurant was tasty and service was quick. The room temperature took a while to cool down, but it was fine after that.',
			'categories' => ['food', 'service', 'room'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 176,
		],
		[
			'name' => 'Olivia B.',
			'rating' => 5,
			'title' => 'Loved the amenities',
			'body' => 'Gym was well-equipped and not crowded. Everything felt polished and thoughtfully designed. Would recommend for business trips too.',
			'categories' => ['amenities', 'service', 'cleanliness'],
			'image' => $pickSeedImage(),
			'created_at' => time() - 3600 * 190,
		],
	];
}
